Add check for 64bit builtin atomics (#18565)
Compilers for some architectures e.g. RISCV32 do not have 64bit atomics
therefore, its important to deduce that and use it to pass right flags to
compiler to use them, e.g. h2o module

Fixes
nection.c.o): in function `h2o_create_connection':
| /usr/src/debug/netdata/1.47.1/src/web/server/h2o/libh2o/include/h2o.h:1917:(.text.create_conn+0x5e): undefined reference to `__sync_add_and_fetch_8'
| collect2: error: ld returned 1 exit status