stacktrace-common: define USE_NOTRACE if no HAVE_BACKTRACE
otherwise, for example, musl doesn't have backtrace() available,
if no ENABLE_LIBUNWIND/ENABLE_LIBBACKTRACE, then build is failed
with message (and many more) like below:

> undefined reference to `stacktrace_flush'

because USE_LIBBACKTRACE/USE_LIBUNWIND/USE_BACKTRACE/USE_NOTRACE are all
undefined.

Signed-off-by: Z. Liu <zhixu.liu@gmail.com>