add missing <dlfcn.h> for stacktrace/libunwind
stacktrace-libunwind.c:170:13: error: call to undeclared function 'dladdr'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

Signed-off-by: Z. Liu <zhixu.liu@gmail.com>