[WIP] Need to change branches to chase symbol-linking errors.
This is roughly how we will fix the problem with --disable-lto, by moving the _dns variable
into the POLLJOB so that we don't need a global between the web_server and socket units.
This won't work yet, still looking into why this now happens:

/usr/bin/ld: /tmp/cczYIfV6.ltrans6.ltrans.o:(.data.rel+0x258): undefined reference to `do_proc_pagetypeinfo'