tests/profile: Fix the building of the tests
The tests were failing to build at the linker stage with numerous
'undefined reference to 'xxxxxx' errors.

Fixing these generally required adding dummy functions that are called
but don't actually need to do anything. e.g send_statistics() which ends
up getting called by libnetdata/log/log.c from the fatal_int() function.

They also generally required the including of database/rrdcalc.h and a
dummy variable of char *netdata_configured_host_prefix.

Fixing benchmark-registry.c required a bit more effort. As well as doing
some of the above.

We add in some global variables (struct config netdata_config &
int netdata_anonymous_statistics_enabled) required by some of the linked
against object files.

We need to rename the PERSON struct variable type to REGISTRY_PERSON
(that's what it's typedef'd as in registry/registry_person.h).

Similarly we call the registry_db_save() function rather than
registry_save() as the latter doesn't exist.

We then change calls to timems() (this existed long ago...) to
now_monotonic_usec(), we use CLOCK_MONOTONIC, since this is used purely
for timing purposes. And yes, despite timems's (milliseconds) name we
are expecting microseconds here.

Finally some Makefile changes. The tests need to link against
libnetdata/socket/security.o and thus everything needs to then link
against OpenSSL (-lssl, -lcrypto). This issue showed up on certain
systems, such as CentOS 7 & Arch Linux.

Also rename LIBNETDATA_FILES to LIBNETDATA_OBJS to more accurately
describe it.

Note: Some of the tests are missing from the Makefile, they will be
added in a subsequent commit.

Signed-off-by: Andrew Clayton <andrew@zeta.digital-domain.net>